baseURL: https://ricardomattos05.github.io/blog_pessoal/
languageCode: en
DefaultContentLanguage: en
title: Blog do Ristat
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
publishDir: docs/
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Ricardo Mattos
  customCss: []
  customJs: []
  description: Enxergando o mundo através dos dados
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/Perfil.JPG
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://de.linkedin.com/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/lxndrblz/anatole/
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:ricardomattos0512@gmail.com
  title: Ricardo Mattos
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
